spring.datasource.url=jdbc:mariadb://${KOMOREBI_DB_HOST}:3306/${KOMOREBI_DB_NAME}
spring.datasource.username=${KOMOREBI_DB_USER}
spring.datasource.password=${KOMOREBI_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
logging.level.org.springframework=ERROR