server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/komorebidb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

jwt.secret=komorebi-super-secret-key-2025-svalero-dam
jwt.expiration=86400000
